# Generated by Django 6.0.3 on 2026-04-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="auctioneer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionparticipant",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionparticipant",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_at",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_auctions",
                through="auctions.AuctionParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionparticipant",
            constraint=models.UniqueConstraint(
                fields=("participant", "auction"), name="unique_participant_per_auction"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["name"], name="auctions_au_name_9aed95_idx"),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["auctioneer"], name="auctions_au_auction_3d517a_idx"
            ),
        ),
    ]
